// <auto-generated />
using System;
using CustomQotd.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomQotd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240826225647_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CustomQotd.Database.Entities.Config", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AdminRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("BasicRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("LogsChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("QotdChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("QotdPingRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QotdTimeHourUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QotdTimeMinuteUtc")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("SuggestionsChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("SuggestionsPingRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("Configs");
                });
#pragma warning restore 612, 618
        }
    }
}
